/**
 * Generated by ForkLaunch
 * File: mikro-orm.config.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { createConfigInjector, getEnvVar, Lifetime } from '@forklaunch/core/services';
import { Migrator } from '@mikro-orm/migrations';
import { TsMorphMetadataProvider } from '@mikro-orm/reflection';
import { number, SchemaValidator, string } from '@dice-roll-node-app/core';
import { defineConfig, Platform, TextType, Type } from '@mikro-orm/core';
import { PostgreSqlDriver } from '@mikro-orm/postgresql';
import dotenv from 'dotenv';
import * as entities from './persistence/entities';

//! Load the environment variables
dotenv.config({ path: getEnvVar('DOTENV_FILE_PATH') });

//! Create the config injector
const configInjector = createConfigInjector(
  SchemaValidator(),
  {
    DB_NAME: {
      lifetime: Lifetime.Singleton,
      type: string,
      value: getEnvVar('DB_NAME')
    },
    DB_HOST: {
      lifetime: Lifetime.Singleton,
      type: string,
      value: getEnvVar('DB_HOST')
    },
    DB_USER: {
      lifetime: Lifetime.Singleton,
      type: string,
      value: getEnvVar('DB_USER')
    },
    DB_PASSWORD: {
      lifetime: Lifetime.Singleton,
      type: string,
      value: getEnvVar('DB_PASSWORD')
    },
    DB_PORT: {
      lifetime: Lifetime.Singleton,
      type: number,
      value: Number(getEnvVar('DB_PORT'))
    }, 
    NODE_ENV: {
      lifetime: Lifetime.Singleton,
      type: string,
      value: getEnvVar('NODE_ENV')
    }
  }
);

//! Validate the config injector
export const validConfigInjector = configInjector.validateConfigSingletons(
  getEnvVar('DOTENV_FILE_PATH')
);
const tokens = validConfigInjector.tokens();

//! Define the mikro-orm options config
const mikroOrmOptionsConfig = defineConfig({
  driver: PostgreSqlDriver,
  dbName: validConfigInjector.resolve(
    tokens.DB_NAME
  ),
  host: validConfigInjector.resolve(
    tokens.DB_HOST
  ),
  user: validConfigInjector.resolve(
    tokens.DB_USER
  ),
  password: validConfigInjector.resolve(
    tokens.DB_PASSWORD
  ),
  port: validConfigInjector.resolve(
    tokens.DB_PORT
  ),
  entities: Object.values(entities),
  metadataProvider: TsMorphMetadataProvider,
  debug: validConfigInjector.resolve(
    tokens.NODE_ENV
  ) === 'development',
  extensions: [Migrator],
  discovery: {
    getMappedType(type: string, platform: Platform) {
      // override the mapping for string properties only
      if (type === 'string') {
        return Type.getType(TextType);
      }

      return platform.getDefaultMappedType(type);
    }
  },
  migrations: {
    path: 'dist/migrations-postgresql',
    pathTs: 'migrations-postgresql'
  },
  seeder: {
    path: 'dist/persistence',
    glob: 'seeder.js'
  }
});

//! Export the mikro-orm options config
export default mikroOrmOptionsConfig;