/**
* Generated by ForkLaunch
* File: registrations.ts
* This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
*/
import { number, SchemaValidator, string } from "@dice-roll-node-app/core";
import { BaseDiceRtrService } from "./services/diceRtr.service";
import { metrics } from "@dice-roll-node-app/monitoring";
import { OpenTelemetryCollector } from "@forklaunch/core/http";
import { createConfigInjector, getEnvVar, Lifetime } from "@forklaunch/core/services";
import { EntityManager, ForkOptions, MikroORM } from "@mikro-orm/core";
import mikroOrmOptionsConfig from "./mikro-orm.config";
import { BaseRollDiceSvcService } from "./services/rollDiceSvc.service";
//! instantiates the config injector
const configInjector = createConfigInjector(SchemaValidator(), { SERVICE_METADATA: {
	lifetime: Lifetime.Singleton,
	type: {
		name: string,
		version: string
	},
	value: {
		name: "dice-roll-node-app-roll-dice-svc",
		version: "0.1.0"
	}
} });
//! defines the environment configuration for the application
const environmentConfig = configInjector.chain({
	PROTOCOL: {
		lifetime: Lifetime.Singleton,
		type: string,
		value: getEnvVar("PROTOCOL")
	},
	HOST: {
		lifetime: Lifetime.Singleton,
		type: string,
		value: getEnvVar("HOST")
	},
	PORT: {
		lifetime: Lifetime.Singleton,
		type: number,
		value: Number(getEnvVar("PORT"))
	},
	VERSION: {
		lifetime: Lifetime.Singleton,
		type: string,
		value: getEnvVar("VERSION") ?? "v1"
	},
	DOCS_PATH: {
		lifetime: Lifetime.Singleton,
		type: string,
		value: getEnvVar("DOCS_PATH") ?? "/docs"
	},
	OTEL_SERVICE_NAME: {
		lifetime: Lifetime.Singleton,
		type: string,
		value: getEnvVar("OTEL_SERVICE_NAME")
	},
	OTEL_LEVEL: {
		lifetime: Lifetime.Singleton,
		type: string,
		value: getEnvVar("OTEL_LEVEL") || "info"
	},
	OTEL_EXPORTER_OTLP_ENDPOINT: {
		lifetime: Lifetime.Singleton,
		type: string,
		value: getEnvVar("OTEL_EXPORTER_OTLP_ENDPOINT")
	}
});
//! defines the runtime dependencies for the application
const runtimeDependencies = environmentConfig.chain({
	MikroORM: {
		lifetime: Lifetime.Singleton,
		type: MikroORM,
		factory: () => MikroORM.initSync(mikroOrmOptionsConfig)
	},
	OpenTelemetryCollector: {
		lifetime: Lifetime.Singleton,
		type: OpenTelemetryCollector,
		factory: ({ OTEL_SERVICE_NAME, OTEL_LEVEL }) => new OpenTelemetryCollector(OTEL_SERVICE_NAME, OTEL_LEVEL || "info", metrics)
	},
	EntityManager: {
		lifetime: Lifetime.Scoped,
		type: EntityManager,
		factory: ({ MikroORM }, _resolve, context) => MikroORM.em.fork(context?.entityManagerOptions as ForkOptions | undefined)
	}
});
//! defines the service dependencies for the application
const serviceDependencies = runtimeDependencies.chain({
	RollDiceSvcService: {
		lifetime: Lifetime.Scoped,
		type: BaseRollDiceSvcService,
		factory: ({ EntityManager, OpenTelemetryCollector }) => new BaseRollDiceSvcService(EntityManager, OpenTelemetryCollector)
	},
	DiceRtrService: {
		lifetime: Lifetime.Scoped,
		type: BaseDiceRtrService,
		factory: ({ EntityManager, OpenTelemetryCollector }, resolve, context) => {
			let em = EntityManager;
			if (context.entityManagerOptions) {
				em = resolve("EntityManager", context);
			}
			return new BaseDiceRtrService(em, OpenTelemetryCollector);
		}
	}
});
//! validates the configuration and returns the dependencies for the application
export const createDependencyContainer = (envFilePath: string) => ({
	ci: serviceDependencies.validateConfigSingletons(envFilePath),
	tokens: serviceDependencies.tokens()
});
