/**
* Generated by ForkLaunch
* File: sdk.ts
* This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
*/
import { SchemaValidator } from "@dice-roll-node-app/core";
import { MapToSdk } from "@forklaunch/core/http";
import { rollDiceSvcGet, rollDiceSvcPost, diceRtrGet, diceRtrPost } from "./api/controllers";
//! defines the sdk type for deep linking with types
export type RollDiceSvcSdk = {
	rollDiceSvc: {
		rollDiceSvcGet: typeof rollDiceSvcGet;
		rollDiceSvcPost: typeof rollDiceSvcPost;
	};
	diceRtr: {
		diceRtrGet: typeof diceRtrGet;
		diceRtrPost: typeof diceRtrPost;
	};
};
//! creates an instance of the sdkClient
export const rollDiceSvcSdkClient = (({
	rollDiceSvc: {
		rollDiceSvcGet,
		rollDiceSvcPost
	},
	diceRtr: {
		diceRtrGet,
		diceRtrPost
	}
}) satisfies RollDiceSvcSdk);
//! exports the universally friendly sdk typings
export type RollDiceSvcSdkClient = MapToSdk<SchemaValidator, RollDiceSvcSdk>;
