/**
* Generated by ForkLaunch
* File: server.ts
* This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
*/
import { forklaunchExpress, SchemaValidator } from "@dice-roll-node-app/core";
import { diceRtrRouter } from "./api/routes/diceRtr.routes";
import { rollDiceSvcRouter } from "./api/routes/rollDiceSvc.routes";
import { ci, tokens } from "./bootstrapper";
import { rollDiceSvcSdkClient } from "./sdk";
/**
* Creates an instance of OpenTelemetryCollector
*/
const openTelemetryCollector = ci.resolve(tokens.OpenTelemetryCollector);
/**
* Creates an instance of forklaunchExpress
*/
const app = forklaunchExpress(SchemaValidator(), openTelemetryCollector);
//! resolves the protocol, host, port, and version from the configuration
const protocol = ci.resolve(tokens.PROTOCOL);
const host = ci.resolve(tokens.HOST);
const port = ci.resolve(tokens.PORT);
const version = ci.resolve(tokens.VERSION);
const docsPath = ci.resolve(tokens.DOCS_PATH);
//! mounts the routes to the app
app.use(rollDiceSvcRouter);
app.use(diceRtrRouter);
//! mounts the sdk to the app
app.registerSdks(rollDiceSvcSdkClient);
//! starts the server
app.listen(port, host, () => {
	openTelemetryCollector.info(`🎉 RollDiceSvc Server is running at ${protocol}://${host}:${port} 🎉.
    // An API reference can be accessed at ${protocol}://${host}:${port}/api/${version}${docsPath}`);
});
