/**
 * Generated by ForkLaunch
 * File: diceRtr.controller.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { handlers, schemaValidator } from '@dice-roll-node-app/core';
import { ci, tokens } from '../../bootstrapper';
import {
  DiceRtrCreateSessionResponseSchema,
  DiceRtrRequestSchema,
  DiceRtrResponseSchema,
  DiceRtrRollRequestSchema,
  DiceRtrRollResponseSchema,
  DiceRtrStatsQuerySchema,
  DiceRtrStatsResponseSchema
} from '../../domain/schemas/diceRtr.schema';

const scopeFactory = () => ci.createScope();
// serviceFactory returns a new service instance on demand
const serviceFactory = ci.scopedResolver(tokens.DiceRtrService);
// openTelemetryCollector for collecting logs and metrics with appropriate context
const openTelemetryCollector = ci.resolve(tokens.OpenTelemetryCollector);

// GET endpoint handler that returns a simple message
export const diceRtrGet = handlers.get(
  schemaValidator,
  '/',
  {
    name: 'Dice Rtr Get',
    summary: 'Gets Dice Rtr',
    responses: {
      200: DiceRtrResponseSchema
    }
  },
  async (_req, res) => {
    res.status(200).json({ message: 'hello, world!' });
  }
);

// POST endpoint handler that returns a simple message
export const diceRtrPost = handlers.post(
  schemaValidator,
  '/',
  {
    name: 'Dice Rtr Post',
    summary: 'Posts Dice Rtr',
    body: DiceRtrRequestSchema,
    responses: {
      200: DiceRtrResponseSchema
    }
  },
  async (_req, res) => {
    res.status(200).json({ message: 'hello, world!' });
  }
);

// Session creation endpoint
export const diceRtrCreateSession = handlers.post(
  schemaValidator,
  '/session',
  {
    name: 'Create Dice Session',
    summary: 'Creates a new rolling session and returns its ID',
    responses: {
      200: DiceRtrCreateSessionResponseSchema
    }
  },
  async (_req, res) => {
    res
      .status(200)
      .json(await serviceFactory(scopeFactory()).diceRtrCreateSession());
  }
);

// Roll dice endpoint
export const diceRtrRoll = handlers.post(
  schemaValidator,
  '/roll',
  {
    name: 'Roll Dice',
    summary: 'Rolls a die with the specified number of sides within a session',
    body: DiceRtrRollRequestSchema,
    responses: {
      200: DiceRtrRollResponseSchema
    }
  },
  async (req, res) => {
    res
      .status(200)
      .json(await serviceFactory(scopeFactory()).diceRtrRoll(req.body));
  }
);

// Stats endpoint — supports ?scope=session&sessionId=<id> or ?scope=all (default)
export const diceRtrStats = handlers.get(
  schemaValidator,
  '/stats',
  {
    name: 'Get Dice Roll Statistics',
    summary:
      'Returns roll statistics and histogram data, optionally scoped to a session',
    query: DiceRtrStatsQuerySchema,
    responses: {
      200: DiceRtrStatsResponseSchema
    }
  },
  async (req, res) => {
    res
      .status(200)
      .json(
        await serviceFactory(scopeFactory()).diceRtrStats(
          req.query as { scope?: string; sessionId?: string }
        )
      );
  }
);
