/**
 * Generated by ForkLaunch
 * File: diceRtr.controller.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { handlers, schemaValidator } from '@dice-roll-node-app/core';
import { ci, tokens } from '../../bootstrapper';
import { DiceRtrRollRequestMapper, DiceRtrRollResponseMapper } from '../../domain/mappers/diceRtr.mappers';
import { DiceRtrRequestSchema, DiceRtrResponseSchema, DiceRtrStatsResponseSchema } from '../../domain/schemas/diceRtr.schema';

//! resolve the dependencies
//! scopeFactory creates a new dependency injection scope for the service
const scopeFactory = () => ci.createScope();
// serviceFactory returns a new service instance on demand
const serviceFactory = ci.scopedResolver(tokens.DiceRtrService);
// openTelemetryCollector for collecting logs and metrics with appropriate context
const openTelemetryCollector = ci.resolve(tokens.OpenTelemetryCollector);

// GET endpoint handler that returns a simple message
export const diceRtrGet = handlers.get(
  schemaValidator,
  '/',
  {
    name: 'Dice Rtr Get',
    summary: 'Gets Dice Rtr',
    responses: {
      200: DiceRtrResponseSchema
    }
  },
  async (req, res) => {
    res.status(200).json({
      message: 'hello, world!'
    });
  }
);

// POST endpoint handler that returns a simple message
export const diceRtrPost = handlers.post(
  schemaValidator,
  '/',
  {
    name: 'Dice Rtr Post',
    summary: 'Posts Dice Rtr',
    body: DiceRtrRequestSchema,
    responses: {
      200: DiceRtrResponseSchema
    }
  },
  async (req, res) => {
    res.status(200).json({
      message: 'hello, world!'
    });
  }
);

// Roll dice endpoint
export const diceRtrRoll = handlers.post(
  schemaValidator,
  '/roll',
  {
    name: 'Roll Dice',
    summary: 'Rolls a dice with specified number of sides',
    body: DiceRtrRollRequestMapper.schema,
    responses: {
      200: DiceRtrRollResponseMapper.schema
    }
  },
  async (req, res) => {
    res.status(200).json(
      await serviceFactory(scopeFactory()).diceRtrRoll(req.body)
    );
  }
);

// Stats endpoint
export const diceRtrStats = handlers.get(
  schemaValidator,
  '/stats',
  {
    name: 'Get Dice Roll Statistics',
    summary: 'Returns statistics about all dice rolls',
    responses: {
      200: DiceRtrStatsResponseSchema
    }
  },
  async (req, res) => {
    res.status(200).json(
      await serviceFactory(scopeFactory()).diceRtrStats()
    );
  }
);