/**
 * Generated by ForkLaunch
 * File: rollDiceSvc.controller.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { handlers, schemaValidator } from '@dice-roll-node-app/core';
import { RollDiceSvcRequestMapper, RollDiceSvcResponseMapper } from '../../domain/mappers/rollDiceSvc.mappers';
import { ci, tokens } from '../../bootstrapper';

//! resolve the dependencies
//! scopeFactory creates a new dependency injection scope for the service
const scopeFactory = () => ci.createScope();
// serviceFactory returns a new service instance on demand
const serviceFactory = ci.scopedResolver(tokens.RollDiceSvcService);
// openTelemetryCollector for collecting logs and metrics with appropriate context
const openTelemetryCollector = ci.resolve(tokens.OpenTelemetryCollector);

  // GET endpoint handler that returns a simple message
export const rollDiceSvcGet = handlers.get(
  schemaValidator,
  '/',
  {
    name: 'Roll Dice Svc Get',
    summary: 'Gets Roll Dice Svc',
    responses: {
      // specifies the success response schema using Mapper constructs
      200: RollDiceSvcResponseMapper.schema
    }
  },
  async (req, res) => {
    res.status(200).json({
      message: 'RollDiceSvc'
    });
  }
);

// POST endpoint handler that processes request body and returns response from service
export const rollDiceSvcPost = handlers.post(
  schemaValidator,
  '/',
  {
    name: 'Roll Dice Svc Post', 
    summary: 'Posts Roll Dice Svc',
    // specifies the request body schema using Mapper constructs
    body: RollDiceSvcRequestMapper.schema,
    responses: {
      // specifies the success response schema using Mapper constructs
      200: RollDiceSvcResponseMapper.schema
    }
  },
  async (req, res) => {
    res
      .status(200)
      .json(
        // constructs a new service instance using the scopeFactory and calls the rollDiceSvcPost method
        await serviceFactory(
          scopeFactory()
        ).rollDiceSvcPost(req.body)
      );
  }
);