/**
 * Generated by ForkLaunch
 * File: diceRtr.test.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import {
  cleanupTestDatabase,
  clearDatabase,
  mockDiceRtrData,
  mockRollData,
  setupTestData,
  setupTestDatabase,
  TEST_SESSION_ID,
  TestSetupResult
} from './test-utils';

describe('DiceRtr Routes E2E Tests', () => {
  let orm: TestSetupResult['orm'];

  beforeAll(async () => {
    const setup = await setupTestDatabase();
    orm = setup.orm;
  }, 60000);

  beforeEach(async () => {
    await clearDatabase({ orm });
    if (!orm) throw new Error('ORM not initialized');
    const em = orm.em.fork();
    await setupTestData(em);
  });

  afterAll(async () => {
    await cleanupTestDatabase();
  }, 30000);

  // ─── GET / ────────────────────────────────────────────────────────────────

  describe('GET /dice-rtr - diceRtrGet', () => {
    it('should return a 200 hello response', async () => {
      const { diceRtrGetRoute } = await import('../api/routes/diceRtr.routes');
      const response = await diceRtrGetRoute.sdk.diceRtrGet();
      expect(response.code).toBe(200);
      expect(response.response).toBeDefined();
    });
  });

  // ─── POST / ───────────────────────────────────────────────────────────────

  describe('POST /dice-rtr - diceRtrPost', () => {
    it('should return 200 for a valid body', async () => {
      const { diceRtrPostRoute } = await import('../api/routes/diceRtr.routes');
      const response = await diceRtrPostRoute.sdk.diceRtrPost({
        body: mockDiceRtrData
      });
      expect(response.code).toBe(200);
      if (response.code === 200) {
        expect(response.response.message).toBeDefined();
      }
    });

    it('should reject an empty message', async () => {
      const { diceRtrPostRoute } = await import('../api/routes/diceRtr.routes');
      try {
        await diceRtrPostRoute.sdk.diceRtrPost({ body: { message: '' } });
        expect(true).toBe(false);
      } catch (error: unknown) {
        expect(error).toBeDefined();
      }
    });
  });

  // ─── POST /session ────────────────────────────────────────────────────────

  describe('POST /dice-rtr/session - diceRtrCreateSession', () => {
    it('should create a session and return sessionId and createdAt', async () => {
      const { diceRtrSessionRoute } = await import('../api/routes/diceRtr.routes');
      const response = await diceRtrSessionRoute.sdk.createDiceSession();
      expect(response.code).toBe(200);
      if (response.code === 200) {
        expect(response.response.sessionId).toBeDefined();
        expect(typeof response.response.sessionId).toBe('string');
        expect(response.response.sessionId.length).toBeGreaterThan(0);
        expect(response.response.createdAt).toBeDefined();
        expect(() => new Date(response.response.createdAt)).not.toThrow();
      }
    });

    it('should generate a different sessionId on each call', async () => {
      const { diceRtrSessionRoute } = await import('../api/routes/diceRtr.routes');
      const r1 = await diceRtrSessionRoute.sdk.createDiceSession();
      const r2 = await diceRtrSessionRoute.sdk.createDiceSession();
      expect(r1.code).toBe(200);
      expect(r2.code).toBe(200);
      if (r1.code === 200 && r2.code === 200) {
        expect(r1.response.sessionId).not.toBe(r2.response.sessionId);
      }
    });
  });

  // ─── POST /roll ───────────────────────────────────────────────────────────

  describe('POST /dice-rtr/roll - diceRtrRoll', () => {
    it('should roll a d6 and return a valid result', async () => {
      const { diceRtrRollRoute } = await import('../api/routes/diceRtr.routes');
      const response = await diceRtrRollRoute.sdk.rollDice({
        body: mockRollData
      });
      expect(response.code).toBe(200);
      if (response.code === 200) {
        expect(response.response.dieType).toBe('d6');
        expect(response.response.result).toBeGreaterThanOrEqual(1);
        expect(response.response.result).toBeLessThanOrEqual(6);
        expect(response.response.id).toBeDefined();
        expect(response.response.sessionId).toBe(TEST_SESSION_ID);
        expect(response.response.createdAt).toBeDefined();
      }
    });

    it('should roll different die types within valid ranges', async () => {
      const { diceRtrRollRoute } = await import('../api/routes/diceRtr.routes');
      const dieTypes = ['d4', 'd6', 'd8', 'd10', 'd12', 'd20'] as const;
      for (const dieType of dieTypes) {
        const response = await diceRtrRollRoute.sdk.rollDice({
          body: { dieType, sessionId: TEST_SESSION_ID }
        });
        expect(response.code).toBe(200);
        if (response.code === 200) {
          const max = parseInt(dieType.replace('d', ''));
          expect(response.response.result).toBeGreaterThanOrEqual(1);
          expect(response.response.result).toBeLessThanOrEqual(max);
        }
      }
    });

    it('should persist the roll to the database with the correct sessionId', async () => {
      const { diceRtrRollRoute } = await import('../api/routes/diceRtr.routes');
      await diceRtrRollRoute.sdk.rollDice({ body: mockRollData });

      if (!orm) throw new Error('ORM not initialized');
      const em = orm.em.fork();
      const { DiceRtrRecord } = await import('../persistence/entities/diceRtrRecord.entity');
      const records = await em.find(DiceRtrRecord, {
        dieType: 'd6',
        sessionId: TEST_SESSION_ID
      });
      expect(records.length).toBeGreaterThan(0);
      const last = records[records.length - 1];
      expect(last.sessionId).toBe(TEST_SESSION_ID);
      expect(last.result).toBeGreaterThanOrEqual(1);
      expect(last.result).toBeLessThanOrEqual(6);
    });

    it('should produce a deterministic result for the same seed inputs', async () => {
      // Two rolls at different real-clock times will differ, but calling
      // rollDieWithSeed directly with identical inputs always agrees.
      // Here we verify the API wires through: same sessionId + same dieType
      // rolled twice produces results in the valid range.
      const { diceRtrRollRoute } = await import('../api/routes/diceRtr.routes');
      const r1 = await diceRtrRollRoute.sdk.rollDice({ body: mockRollData });
      const r2 = await diceRtrRollRoute.sdk.rollDice({ body: mockRollData });
      expect(r1.code).toBe(200);
      expect(r2.code).toBe(200);
      if (r1.code === 200 && r2.code === 200) {
        expect(r1.response.result).toBeGreaterThanOrEqual(1);
        expect(r2.response.result).toBeGreaterThanOrEqual(1);
      }
    });

    it('should reject invalid die types', async () => {
      const { diceRtrRollRoute } = await import('../api/routes/diceRtr.routes');
      for (const bad of ['d1', 'd0', 'invalid', '']) {
        try {
          await diceRtrRollRoute.sdk.rollDice({
            body: { dieType: bad, sessionId: TEST_SESSION_ID }
          });
          expect(true).toBe(false);
        } catch (error: unknown) {
          expect(error).toBeDefined();
        }
      }
    });
  });

  // ─── GET /stats ───────────────────────────────────────────────────────────

  describe('GET /dice-rtr/stats - diceRtrStats', () => {
    it('should return stats for all rolls (default scope)', async () => {
      const { diceRtrStatsRoute } = await import('../api/routes/diceRtr.routes');
      const response = await diceRtrStatsRoute.sdk.getDiceRollStatistics();
      expect(response.code).toBe(200);
      if (response.code === 200) {
        expect(typeof response.response.totalRolls).toBe('number');
        expect(response.response.byDieType).toBeDefined();
      }
    });

    it('should include histogram distribution per die type', async () => {
      const { diceRtrRollRoute, diceRtrStatsRoute } = await import('../api/routes/diceRtr.routes');

      // Roll a d6 so there is at least one persisted record
      await diceRtrRollRoute.sdk.rollDice({ body: mockRollData });

      const response = await diceRtrStatsRoute.sdk.getDiceRollStatistics();
      expect(response.code).toBe(200);
      if (response.code === 200) {
        const d6 = response.response.byDieType['d6'];
        expect(d6).toBeDefined();
        expect(d6.count).toBeGreaterThanOrEqual(1);
        expect(d6.distribution).toBeDefined();
        expect(typeof d6.average).toBe('number');
        expect(d6.min).toBeGreaterThanOrEqual(1);
        expect(d6.max).toBeLessThanOrEqual(6);
      }
    });

    it('should return scoped stats when scope=session&sessionId is provided', async () => {
      const { diceRtrRollRoute, diceRtrStatsRoute } = await import('../api/routes/diceRtr.routes');

      // Create a second session and roll under it to pollute "all" scope
      const otherSession = 'ffffffff-0000-1111-2222-333333333333';
      await diceRtrRollRoute.sdk.rollDice({
        body: { dieType: 'd20', sessionId: otherSession }
      });

      // Roll under the test session
      await diceRtrRollRoute.sdk.rollDice({ body: mockRollData });

      const response = await diceRtrStatsRoute.sdk.getDiceRollStatistics({
        query: { scope: 'session', sessionId: TEST_SESSION_ID }
      });
      expect(response.code).toBe(200);
      if (response.code === 200) {
        // The d20 roll from otherSession must NOT appear
        const d20 = response.response.byDieType['d20'];
        expect(d20).toBeUndefined();
        // The d6 from the test session should appear
        const d6 = response.response.byDieType['d6'];
        expect(d6).toBeDefined();
      }
    });

    it('should return all rolls when scope=all', async () => {
      const { diceRtrRollRoute, diceRtrStatsRoute } = await import('../api/routes/diceRtr.routes');

      await diceRtrRollRoute.sdk.rollDice({ body: { dieType: 'd4', sessionId: 'session-one' } });
      await diceRtrRollRoute.sdk.rollDice({ body: { dieType: 'd12', sessionId: 'session-two' } });

      const response = await diceRtrStatsRoute.sdk.getDiceRollStatistics({
        query: { scope: 'all' }
      });
      expect(response.code).toBe(200);
      if (response.code === 200) {
        expect(response.response.totalRolls).toBeGreaterThanOrEqual(2);
      }
    });
  });
});
