/**
 * Generated by ForkLaunch
 * File: rollDiceSvc.test.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import {
  cleanupTestDatabase,
  clearDatabase,
  mockRollDiceSvcData,
  setupTestData,
  setupTestDatabase,
  TestSetupResult
} from './test-utils';

describe('RollDiceSvc Routes E2E Tests', () => {
  let orm: TestSetupResult['orm'];
  
  
  

  beforeAll(async () => {
    const setup = await setupTestDatabase();
    orm = setup.orm;
    
    
    
  }, 60000);

  beforeEach(async () => {
    await clearDatabase({ orm });
    if (!orm) throw new Error('ORM not initialized');
    const em = orm.em.fork();
    await setupTestData(em);
  });

  afterAll(async () => {
    await cleanupTestDatabase();
  }, 30000);

  describe('GET /rollDiceSvc - rollDiceSvcGet', () => {
    it('should handle rollDiceSvc get request successfully', async () => {
      const { rollDiceSvcGetRoute } = await import(
        '../api/routes/rollDiceSvc.routes'
      );

      const response = await rollDiceSvcGetRoute.sdk.rollDiceSvcGet();

      expect(response.code).toBe(200);
      expect(response.response).toBeDefined();
    });
  });

  describe('POST /rollDiceSvc - rollDiceSvcPost', () => {
    it('should handle rollDiceSvc request successfully', async () => {
      const { rollDiceSvcPostRoute } = await import(
        '../api/routes/rollDiceSvc.routes'
      );

      const response = await rollDiceSvcPostRoute.sdk.rollDiceSvcPost({
        body: mockRollDiceSvcData
      });

      expect(response.code).toBe(200);
      expect(response.response).toBeDefined();
      if (response.code === 200) {
        expect(response.response.message).toBeDefined();
      }
    });

    it('should handle validation errors', async () => {
      const { rollDiceSvcPostRoute } = await import(
        '../api/routes/rollDiceSvc.routes'
      );

      const invalidData = {
        message: ''
      };

      try {
        await rollDiceSvcPostRoute.sdk.rollDiceSvcPost({
          body: invalidData
        });
        expect(true).toBe(false);
      } catch (error: unknown) {
        expect(error).toBeDefined();
      }
    });
    

    it('should persist data to database', async () => {
      const { rollDiceSvcPostRoute } = await import(
        '../api/routes/rollDiceSvc.routes'
      );

      await rollDiceSvcPostRoute.sdk.rollDiceSvcPost({
        body: mockRollDiceSvcData
      });

      if (!orm) throw new Error('ORM not initialized');
      const em = orm.em.fork();
      const { RollDiceSvcRecord } = await import(
        '../persistence/entities/rollDiceSvcRecord.entity'
      );

      const records = await em.find(RollDiceSvcRecord, {
        message: mockRollDiceSvcData.message
      });

      expect(records.length).toBeGreaterThan(0);
    });
    
  });
});