/**
* Generated by ForkLaunch
* File: test-utils.ts
* This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
*/
import { getEnvVar } from "@forklaunch/common";
import { BlueprintTestHarness, clearTestDatabase, DatabaseType, TEST_TOKENS, TestSetupResult } from "@forklaunch/testing";
import { EntityManager } from "@mikro-orm/core";
import dotenv from "dotenv";
import * as path from "path";
export { TEST_TOKENS, TestSetupResult };
let harness: BlueprintTestHarness;
dotenv.config({ path: path.join(__dirname, "../.env.test") });
export const setupTestDatabase = async (): Promise<TestSetupResult> => {
	harness = new BlueprintTestHarness({
		getConfig: async () => {
			const { default: config } = await import("../mikro-orm.config");
			return config;
		},
		databaseType: getEnvVar("DATABASE_TYPE") as DatabaseType,
		useMigrations: false,
		needsRedis: false,
		customEnvVars: {
			PROTOCOL: "http",
			HOST: "localhost",
			PORT: "3000",
			VERSION: "v1",
			DOCS_PATH: "/docs",
			OTEL_SERVICE_NAME: "test-service",
			OTEL_LEVEL: "info",
			OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4318"
		}
	});
	return await harness.setup();
};
export const cleanupTestDatabase = async (): Promise<void> => {
	if (harness) {
		await harness.cleanup();
	}
};
export const clearDatabase = async (options?: {
	orm?: TestSetupResult["orm"];
	redis?: TestSetupResult["redis"];
}): Promise<void> => {
	await clearTestDatabase(options);
};
export const setupTestData = async (em: EntityManager) => {
	const { RollDiceSvcRecord } = await import("../persistence/entities/rollDiceSvcRecord.entity");
	em.create(RollDiceSvcRecord, {
		id: "123e4567-e89b-12d3-a456-426614174000",
		message: "Test message",
		createdAt: new Date(),
		updatedAt: new Date()
	});
	const { DiceRtrRecord } = await import("../persistence/entities/diceRtrRecord.entity");
	em.create(DiceRtrRecord, {
		id: "123e4567-e89b-12d3-a456-426614174000",
		dieType: "d6",
		result: 3,
		createdAt: new Date(),
		updatedAt: new Date()
	});
	await em.flush();
};
export const mockRollDiceSvcData = { message: "New test message" };
export const mockDiceRtrData = { message: "New test message" }; // For POST endpoint that accepts message
