/**
 * Generated by ForkLaunch
 * File: diceRtr.routes.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { forklaunchRouter, schemaValidator } from '@dice-roll-node-app/core';
import { ci, tokens } from '../../bootstrapper';
import {
  diceRtrCreateSession,
  diceRtrGet,
  diceRtrPost,
  diceRtrRoll,
  diceRtrStats
} from '../controllers/diceRtr.controller';

// resolve the dependencies
const openTelemetryCollector = ci.resolve(tokens.OpenTelemetryCollector);

export const diceRtrRouter = forklaunchRouter(
  '/dice-rtr',
  schemaValidator,
  openTelemetryCollector
);

// Mount the routes
export const diceRtrGetRoute = diceRtrRouter.get('/', diceRtrGet);
export const diceRtrPostRoute = diceRtrRouter.post('/', diceRtrPost);
export const diceRtrSessionRoute = diceRtrRouter.post(
  '/session',
  diceRtrCreateSession
);
export const diceRtrRollRoute = diceRtrRouter.post('/roll', diceRtrRoll);
export const diceRtrStatsRoute = diceRtrRouter.get('/stats', diceRtrStats);
