/**
 * Generated by ForkLaunch
 * File: rollDiceSvc.routes.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { forklaunchRouter, schemaValidator } from '@dice-roll-node-app/core';
import { rollDiceSvcGet, rollDiceSvcPost } from '../controllers/rollDiceSvc.controller';
import { ci, tokens } from '../../bootstrapper';


// resolve the dependencies
const openTelemetryCollector = ci.resolve(tokens.OpenTelemetryCollector);

// defines the router for the rollDiceSvc routes
export const rollDiceSvcRouter = forklaunchRouter(
  '/roll-dice-svc',
  schemaValidator, 
  openTelemetryCollector
);

// mount the routes
export const rollDiceSvcGetRoute = rollDiceSvcRouter.get('/', rollDiceSvcGet);
export const rollDiceSvcPostRoute = rollDiceSvcRouter.post('/', rollDiceSvcPost);