/**
 * Generated by ForkLaunch
 * File: diceRtrRecord.seeder.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { EntityManager } from "@mikro-orm/core";
import { Seeder } from "@mikro-orm/seeder";
import { diceRtrRecord } from "../seed.data";
import { DiceRtrRecord } from "../entities/diceRtrRecord.entity";

export class DiceRtrRecordSeeder extends Seeder {
  async run(em: EntityManager): Promise<void> {
    const record = em.create(DiceRtrRecord, diceRtrRecord);
    return em.persistAndFlush(record);
  }
}