export { DiceRtrRecordSeeder } from "./diceRtrRecord.seeder";
/**
* Generated by ForkLaunch
* File: index.ts
* This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
*/
export { RollDiceSvcRecordSeeder } from "./rollDiceSvcRecord.seeder";
