/**
* Generated by ForkLaunch
* File: seed.data.ts
* This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
*/
import { RequiredEntityData } from "@mikro-orm/core";
import { DiceRtrRecord } from "./entities/diceRtrRecord.entity";
import { RollDiceSvcRecord } from "./entities/rollDiceSvcRecord.entity";
//! Begin seed data
export const rollDiceSvcRecord = (({
	message: "Hello, world!",
	createdAt: new Date(),
	updatedAt: new Date()
}) satisfies RequiredEntityData<RollDiceSvcRecord>);
export const diceRtrRecord = (({
	dieType: "d6",
	result: 3,
	createdAt: new Date(),
	updatedAt: new Date()
}) satisfies RequiredEntityData<DiceRtrRecord>);
