/**
* Generated by ForkLaunch
* File: universalSdk.ts
* This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
*/
import { universalSdk } from "@forklaunch/universal-sdk";
import { RollDiceSvcSdkClient } from "@dice-roll-node-app/roll-dice-svc";
export const rollDiceSvcSdkClient = universalSdk<RollDiceSvcSdkClient>;
