/**
 * Generated by ForkLaunch
 * File: diceRtr.service.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { Metrics } from '@dice-roll-node-app/monitoring';
import { rollDieWithSeed } from '@dice-roll-node-app/seeded-random-number';
import { OpenTelemetryCollector } from '@forklaunch/core/http';
import { EntityManager } from '@mikro-orm/core';
import { randomUUID } from 'crypto';
import { DiceRtrService } from '../domain/interfaces/diceRtr.interface';
import {
  DiceRtrCreateSessionResponseDto,
  DiceRtrRollRequestDto,
  DiceRtrRollResponseDto,
  DiceRtrStatsQueryDto,
  DiceRtrStatsResponseDto
} from '../domain/types/diceRtr.types';
import { DiceRtrRecord } from '../persistence/entities/diceRtrRecord.entity';

export class BaseDiceRtrService implements DiceRtrService {
  private entityManager: EntityManager;
  private readonly openTelemetryCollector: OpenTelemetryCollector<Metrics>;

  constructor(
    entityManager: EntityManager,
    openTelemetryCollector: OpenTelemetryCollector<Metrics>
  ) {
    this.entityManager = entityManager;
    this.openTelemetryCollector = openTelemetryCollector;
  }

  diceRtrCreateSession = async (): Promise<DiceRtrCreateSessionResponseDto> => {
    const sessionId = randomUUID();
    const createdAt = new Date();

    this.openTelemetryCollector.info('Session created', { sessionId });

    return {
      sessionId,
      createdAt: createdAt.toISOString()
    };
  };

  diceRtrRoll = async (
    dto: DiceRtrRollRequestDto
  ): Promise<DiceRtrRollResponseDto> => {
    const sides = parseInt(dto.dieType.replace('d', ''));
    if (isNaN(sides) || sides < 2) {
      throw new Error(
        `Invalid die type: ${dto.dieType}. Use format d4, d6, d12, d20, etc.`
      );
    }

    const now = new Date();

    // Deterministic roll: seed comes from the shared seeded-random-number library.
    // Seed inputs: UTC epoch ms + sessionId + dieType — fully auditable from DB.
    const result = rollDieWithSeed({
      timestampUtcMs: now.getTime(),
      sessionId: dto.sessionId,
      dieType: dto.dieType,
      sides
    });

    const entity = this.entityManager.create(DiceRtrRecord, {
      dieType: dto.dieType,
      result,
      sessionId: dto.sessionId,
      createdAt: now,
      updatedAt: now
    });

    await this.entityManager.persistAndFlush(entity);

    this.openTelemetryCollector.info('Dice rolled', {
      dieType: dto.dieType,
      result: entity.result,
      sessionId: dto.sessionId
    });

    return {
      dieType: entity.dieType,
      result: entity.result,
      id: entity.id,
      sessionId: entity.sessionId,
      createdAt: entity.createdAt.toISOString()
    };
  };

  diceRtrStats = async (
    query?: DiceRtrStatsQueryDto
  ): Promise<DiceRtrStatsResponseDto> => {
    const isSessionScope = query?.scope === 'session' && query?.sessionId;

    const rolls = isSessionScope
      ? await this.entityManager.find(DiceRtrRecord, {
          sessionId: query!.sessionId
        })
      : await this.entityManager.find(DiceRtrRecord, {});

    const byDieType: Record<
      string,
      {
        count: number;
        average: number;
        min: number;
        max: number;
        distribution: Record<string, number>;
      }
    > = {};

    rolls.forEach((roll) => {
      if (!byDieType[roll.dieType]) {
        byDieType[roll.dieType] = {
          count: 0,
          average: 0,
          min: Infinity,
          max: -Infinity,
          distribution: {}
        };
      }

      const stats = byDieType[roll.dieType];
      stats.count++;
      stats.min = Math.min(stats.min, roll.result);
      stats.max = Math.max(stats.max, roll.result);

      const face = String(roll.result);
      stats.distribution[face] = (stats.distribution[face] ?? 0) + 1;
    });

    Object.keys(byDieType).forEach((dieType) => {
      const dieRolls = rolls.filter((r) => r.dieType === dieType);
      const sum = dieRolls.reduce((acc, r) => acc + r.result, 0);
      byDieType[dieType].average = sum / dieRolls.length;
    });

    return {
      totalRolls: rolls.length,
      byDieType
    };
  };
}
