/**
 * Generated by ForkLaunch
 * File: rollDiceSvc.service.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { OpenTelemetryCollector } from '@forklaunch/core/http';
import { EntityManager } from '@mikro-orm/core';
import { SchemaValidator } from '@dice-roll-node-app/core';
import { Metrics } from '@dice-roll-node-app/monitoring';
import { RollDiceSvcService } from '../domain/interfaces/rollDiceSvc.interface';
import { 
  RollDiceSvcRequestDto, 
  RollDiceSvcResponseDto 
} from '../domain/types/rollDiceSvc.types';
import {
  RollDiceSvcRequestMapper,
  RollDiceSvcResponseMapper
} from '../domain/mappers/rollDiceSvc.mappers';

// BaseRollDiceSvcService class that implements the RollDiceSvcService interface
export class BaseRollDiceSvcService implements RollDiceSvcService { 
  private entityManager: EntityManager;
  private readonly openTelemetryCollector: OpenTelemetryCollector<Metrics>;

  constructor(
    entityManager: EntityManager, 
    openTelemetryCollector: OpenTelemetryCollector<Metrics>
  ) { 
    this.entityManager = entityManager;
    this.openTelemetryCollector = openTelemetryCollector;
  }

  // rollDiceSvcPost method that implements the RollDiceSvcService interface
  rollDiceSvcPost = async (
    dto: RollDiceSvcRequestDto
  ): Promise<RollDiceSvcResponseDto> => {
    const entity = await RollDiceSvcRequestMapper.toEntity(
      dto,
      this.entityManager
    );
    
    await this.entityManager.persistAndFlush(entity);
    
    return RollDiceSvcResponseMapper.toDto(entity);
  };
}