/**
 * Generated by ForkLaunch
 * File: diceRtrRecord.entity.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { SqlBaseEntity } from '@dice-roll-node-app/core';
import { Entity, Index, Property } from '@mikro-orm/core';

@Entity()
export class DiceRtrRecord extends SqlBaseEntity {
  @Property()
  dieType!: string; // e.g., "d4", "d6", "d8", "d10", "d12", "d20"

  @Property()
  result!: number; // The rolled value (1 to dieType number)

  @Property()
  @Index()
  sessionId!: string; // UUID grouping rolls within a session
}
