/**
 * Generated by ForkLaunch
 * File: rollDiceSvcRecord.entity.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { Entity, Property } from '@mikro-orm/core';
import { SqlBaseEntity } from '@dice-roll-node-app/core';

// Entity class that defines the structure of the RollDiceSvcRecordtable
@Entity()
export class RollDiceSvcRecord extends SqlBaseEntity {
  // message property that stores a message string
  @Property()
  message!: string;
}