/**
 * Generated by ForkLaunch
 * File: diceRtr.types.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { SchemaValidator } from '@dice-roll-node-app/core';
import { Schema } from '@forklaunch/validator';
import { DiceRtrRequestSchema, DiceRtrResponseSchema, DiceRtrRollRequestSchema, DiceRtrRollResponseSchema, DiceRtrStatsResponseSchema } from '../schemas/diceRtr.schema';

// Exported type that matches the request schema
export type DiceRtrRequestDto = Schema<typeof DiceRtrRequestSchema, SchemaValidator>;

// Exported type that matches the response schema
export type DiceRtrResponseDto = Schema<typeof DiceRtrResponseSchema, SchemaValidator>;

// Exported types for roll operations
export type DiceRtrRollRequestDto = Schema<typeof DiceRtrRollRequestSchema, SchemaValidator>;
export type DiceRtrRollResponseDto = Schema<typeof DiceRtrRollResponseSchema, SchemaValidator>;
export type DiceRtrStatsResponseDto = Schema<typeof DiceRtrStatsResponseSchema, SchemaValidator>;