/**
 * Generated by ForkLaunch
 * File: rollDiceSvc.types.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { Schema } from '@forklaunch/validator';
import { SchemaValidator } from '@dice-roll-node-app/core';
import { RollDiceSvcRequestSchema, RollDiceSvcResponseSchema } from '../schemas/rollDiceSvc.schema';

// Exported type that matches the request schema
export type RollDiceSvcRequestDto = Schema<typeof RollDiceSvcRequestSchema, SchemaValidator>;

// Exported type that matches the response schema
export type RollDiceSvcResponseDto = Schema<typeof RollDiceSvcResponseSchema, SchemaValidator>;