/**
 * Generated by ForkLaunch
 * File: diceRtr.interface.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import {
  DiceRtrRollRequestDto,
  DiceRtrRollResponseDto,
  DiceRtrStatsResponseDto
} from '../types/diceRtr.types';

// Interface that defines the methods that the DiceRtrService must implement
// export interface DiceRtrService {
//   diceRtrPost: (
//     dto: DiceRtrRequestDto
//   ) => Promise<DiceRtrResponseDto>;
// }

export interface DiceRtrService {
  diceRtrRoll(dto: DiceRtrRollRequestDto): Promise<DiceRtrRollResponseDto>;
  diceRtrStats(): Promise<DiceRtrStatsResponseDto>;
}