/**
 * Generated by ForkLaunch
 * File: rollDiceSvc.interface.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import {
  RollDiceSvcRequestDto,
  RollDiceSvcResponseDto
} from '../types/rollDiceSvc.types';

// Interface that defines the methods that the RollDiceSvcService must implement
export interface RollDiceSvcService {
  rollDiceSvcPost: (
    dto: RollDiceSvcRequestDto
  ) => Promise<RollDiceSvcResponseDto>;
}