{
 "title": "RED",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "label_values(service_name)" },
   {
    "name": "api",
    "label": "API",
    "query": "label_values({service_name=~\"$service\"}, api_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "API Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(api_name) (\n  increase(http_server_duration_seconds_count{\n    service_name=~\"$service\",\n    api_name=~\"$api\",\n    http_response_status_code!~\"4..|5..\"\n  }[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(service_name) (\n  increase(http_server_duration_seconds_count{\n    service_name=~\"$service\",\n    http_response_status_code!~\"4..|5..\"\n  }[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(api_name) (\n  increase(http_server_duration_seconds_count{\n    service_name=~\"$service\",\n    api_name=~\"$api\",\n    http_response_status_code=~\"4..|5..\"\n  }[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(service_name) (\n  increase(http_server_duration_seconds_count{\n    service_name=~\"$service\",\n    http_response_status_code=~\"4..|5..\"\n  }[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "API Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(api_name) (\n  increase(http_server_duration_seconds_sum{service_name=~\"$service\", api_name=~\"$api\"}[$__rate_interval])\n) / sum by(api_name) (\n  increase(http_server_duration_seconds_count{service_name=~\"$service\", api_name=~\"$api\"}[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(service_name) (\n  increase(http_server_duration_seconds_sum{service_name=~\"$service\"}[$__rate_interval])\n) / sum by(service_name) (\n  increase(http_server_duration_seconds_count{service_name=~\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "monitoring"
    }
   ]
  }
 ]
}