/**
 * Generated by ForkLaunch
 * File: diceRtr.schema.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { number, record, string } from '@dice-roll-node-app/core';

// idiomatic validator schema defines the request schema. This should extend the request type
export const DiceRtrRequestSchema = {
    message: string
};

// idiomatic validator schema defines the response schema. This should extend the response type
export const DiceRtrResponseSchema = {
    message: string
};

// Request schema for rolling dice
export const DiceRtrRollRequestSchema = {
    dieType: string // e.g., "d4", "d6", "d12", "d20"
};

// Response schema for roll result
export const DiceRtrRollResponseSchema = {
    dieType: string,
    result: number,
    id: string,
    createdAt: string
};

// Response schema for stats
export const DiceRtrStatsResponseSchema = {
    totalRolls: number,
    byDieType: record(string, {
        count: number,
        average: number,
        min: number,
        max: number
    })
};