/**
 * Generated by ForkLaunch
 * File: diceRtr.mappers.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { schemaValidator } from '@dice-roll-node-app/core';
import {
  requestMapper,
  responseMapper
} from '@forklaunch/core/mappers';
import { EntityManager } from '@mikro-orm/core';
import { DiceRtrRecord } from '../../persistence/entities/diceRtrRecord.entity';
import { DiceRtrRequestSchema, DiceRtrResponseSchema, DiceRtrRollRequestSchema, DiceRtrRollResponseSchema } from '../schemas/diceRtr.schema';

// RequestMapper const that maps a request schema to an entity
export const DiceRtrRequestMapper = requestMapper(
  schemaValidator,
  DiceRtrRequestSchema,
  DiceRtrRecord,
  {
    toEntity: async (dto, em: EntityManager) => {
      // This mapper is for the generic message endpoint
      // Since the entity doesn't have a message field, we'll use a default dieType
      return DiceRtrRecord.create({
        dieType: 'd6',
        result: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, em);
    }
  }
);

// ResponseMapper const that maps an entity to a response schema
export const DiceRtrResponseMapper = responseMapper(
  schemaValidator,
  DiceRtrResponseSchema,
  DiceRtrRecord,
  {
    toDto: async (entity: DiceRtrRecord) => {
      return {
        message: `Dice roll: ${entity.dieType} = ${entity.result}`
      };
    }
  }
);

export const DiceRtrRollRequestMapper = requestMapper(
  schemaValidator,
  DiceRtrRollRequestSchema,
  DiceRtrRecord,
  {
    toEntity: async (dto, em: EntityManager) => {
      // Parse dieType (e.g., "d6" -> 6)
      const sides = parseInt(dto.dieType.replace('d', ''));
      if (isNaN(sides) || sides < 2) {
        throw new Error(`Invalid die type: ${dto.dieType}`);
      }

      // Roll the dice
      const result = Math.floor(Math.random() * sides) + 1;

      return DiceRtrRecord.create({
        dieType: dto.dieType,
        result: result,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, em);
    }
  }
);

export const DiceRtrRollResponseMapper = responseMapper(
  schemaValidator,
  DiceRtrRollResponseSchema,
  DiceRtrRecord,
  {
    toDto: async (entity: DiceRtrRecord) => {
      return {
        dieType: entity.dieType,
        result: entity.result,
        id: entity.id,
        createdAt: entity.createdAt.toISOString()
      };
    }
  }
);