/**
 * Generated by ForkLaunch
 * File: rollDiceSvc.mappers.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import {
  requestMapper,
  responseMapper
} from '@forklaunch/core/mappers';
import { schemaValidator } from '@dice-roll-node-app/core';
import { EntityManager } from '@mikro-orm/core';
import { RollDiceSvcRecord} from '../../persistence/entities/rollDiceSvcRecord.entity';
import { RollDiceSvcRequestSchema, RollDiceSvcResponseSchema } from '../schemas/rollDiceSvc.schema';

// RequestMapper const that maps a request schema to an entity
export const RollDiceSvcRequestMapper = requestMapper(
  schemaValidator,
  RollDiceSvcRequestSchema,
  RollDiceSvcRecord,
  {
    toEntity: async (dto, em: EntityManager) => {
      return RollDiceSvcRecord.create({
        ...dto,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, em);
    }
  }
);

// ResponseMapper const that maps an entity to a response schema
export const RollDiceSvcResponseMapper = responseMapper(
  schemaValidator,
  RollDiceSvcResponseSchema,
  RollDiceSvcRecord,
  {
    toDto: async (entity: RollDiceSvcRecord) => {
      return await entity.read();
    }
  }
);